---
# download_images.yml tasks file for nutanix_prism_role_karbon_enable
- name: Get available karbon images
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/karbon/acs/image/list"
    method: GET
    validate_certs: "{{ role_nutanix_pc_svc_karbon_host_validate_certs }}"
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    status_code: 200
    return_content: true
  register: role_nutanix_pc_svc_karbon_image_list
  ignore_errors: false

- name: Debug role_nutanix_pc_svc_karbon_image_list.json
  ansible.builtin.debug:
    var: role_nutanix_pc_svc_karbon_image_list.json
  when: role_nutanix_pc_svc_karbon_debug

- name: Get list of available image uuids that are available
  ansible.builtin.set_fact:
    role_nutanix_pc_svc_karbon_missing_image_list: >-
      "{{ role_nutanix_pc_svc_karbon_image_list.json
      | community.general.json_query(query)
      | to_json
      | from_json }}"
  vars:
    query: "[?status != 'Downloaded'].{uuid: uuid}"

- name: Debug role_nutanix_pc_svc_karbon_missing_image_list
  ansible.builtin.debug:
    var: role_nutanix_pc_svc_karbon_missing_image_list
  when: role_nutanix_pc_svc_karbon_debug

- name: Download available Karbon image(s)
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/karbon/acs/image/download"
    body:
      uuid: item.uuid
    method: POST
    validate_certs: "{{ role_nutanix_pc_svc_karbon_host_validate_certs }}"
    body_format: json
    status_code: 200
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
  register: role_nutanix_pc_svc_karbon_image_download_task
  ignore_errors: false
  with_items: "{{ role_nutanix_pc_svc_karbon_missing_image_list }}"

- name: Debug role_nutanix_pc_svc_karbon_image_list.json | list | count
  ansible.builtin.debug:
    var: role_nutanix_pc_svc_karbon_image_list.json | list | count
  when: role_nutanix_pc_svc_karbon_debug

- name: Debug role_nutanix_pc_svc_karbon_image_list.json | selectattr('status','equalto','Downloaded') | list | count
  ansible.builtin.debug:
    var: role_nutanix_pc_svc_karbon_image_list.json | selectattr('status','equalto','Downloaded') | list | count
  when: role_nutanix_pc_svc_karbon_debug

- name: Wait for image(s) to complete download
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/karbon/acs/image/list"
    method: GET
    validate_certs: "{{ role_nutanix_pc_svc_karbon_host_validate_certs }}"
    body_format: json
    status_code: 200
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
  register: nutanix_karbon_image_download_list
  ignore_errors: false
  until: >-
    "{{ nutanix_karbon_image_download_list.json
    | selectattr('status', 'equalto', 'Downloaded')
    | list
    | count == nutanix_karbon_image_download_list.json
    | list
    | count }}"
