---
- name: Get Karbon Status
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v1/genesis"
    body:
      value: '{".oid":"ClusterManager",".method":"is_service_enabled",".kwargs":{"service_name":"KarbonUIService"}}'
    method: POST
    validate_certs: "{{ role_nutanix_pc_svc_karbon_host_validate_certs }}"
    body_format: json
    status_code: 200
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
  register: role_nutanix_pc_svc_karbon_service_result
  ignore_errors: false

- name: Debug role_nutanix_pc_svc_karbon_service_result.json
  ansible.builtin.debug:
    var: role_nutanix_pc_svc_karbon_service_result.json
  when: role_nutanix_pc_svc_karbon_debug

- name: Set fact role_nutanix_pc_svc_karbon_status
  ansible.builtin.set_fact:
    role_nutanix_pc_svc_karbon_status: "{{ role_nutanix_pc_svc_karbon_service_result.json | community.general.json_query(query) | to_json | from_json }}"
  vars:
    query: "value"

- name: Debug role_nutanix_pc_svc_karbon_status
  ansible.builtin.debug:
    var: role_nutanix_pc_svc_karbon_status
  when: role_nutanix_pc_svc_karbon_debug

- name: Update fact karbon_enabled if KarbonUIService is enabled
  ansible.builtin.set_fact:
    role_nutanix_pc_svc_karbon_enabled: true
  when:
    - true in role_nutanix_pc_svc_karbon_status[".return"]

- name: Debug role_nutanix_pc_svc_karbon_enabled
  ansible.builtin.debug:
    var: role_nutanix_pc_svc_karbon_enabled
  when: role_nutanix_pc_svc_karbon_debug
